### ISSUE TITLE
Set-up issue tracking.

### ISSUE THREAD

**Issue by dougalf** [dougalf/LolaT#5]
- [X] initial set-up and automation.
- [X] add @dougaljf as collaborator for review purposes
- [x] integration with code repository

**Comment by dougalf** [comment]
Thank-you Github for simplicity of final task ⏩
